//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecurringDebitService.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdaptLead
    {
        public int Id { get; set; }
        public string email { get; set; }
        public string fullname { get; set; }
        public System.DateTime created_at { get; set; }
        public string UUID { get; set; }
        public string fcm_token { get; set; }
        public string app_version { get; set; }
        public string platform { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
