//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecurringDebitService.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaystackRecurringDump
    {
        public int Id { get; set; }
        public string policynumber { get; set; }
        public string productname { get; set; }
        public string logonemail { get; set; }
        public string coresystememail { get; set; }
        public string paystackrawdump { get; set; }
        public System.DateTime dumpdate { get; set; }
        public bool dumpstate { get; set; }
        public string dumpmessage { get; set; }
    }
}
