// <auto-generated />
namespace DataStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class secondmirgration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secondmirgration));
        
        string IMigrationMetadata.Id
        {
            get { return "202009300935110_second mirgration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
